name: CI Build & Test
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'archive/**'
  workflow_dispatch:
    inputs:
      skip_tests:
        description: Skip tests
        type: boolean

jobs:
  lib_cli_package:
    name: Build & Test Lib and CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test
        run: |
          if [[ ${{ inputs.skip_tests }} == true ]]; then
            mvn -DskipTests clean package
          else
            mvn clean package
          fi

      - name: Copy artifacts
        run: mkdir artifacts && cp cli/target/*-dependencies.jar artifacts

      - name: Upload CLI JAR
        uses: actions/upload-artifact@v4
        with:
          name: cli
          path: artifacts