name: CI Build & Test
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  lib_cli_package:
    name: Build & Test Lib and CLI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn clean package
      - run: mkdir artifacts && cp cli/target/*-dependencies.jar artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: Upload CLI JAR
          path: artifacts